version: "3.9"
services:
  db:
    image: pgvector/pgvector:pg16        # PostgreSQL 16 with pgvector pre-installed
    container_name: hotel-db
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER:     ${DB_USER}
      POSTGRES_DB:       ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data   # keeps data between restarts
      - ./init:/docker-entrypoint-initdb.d       # dump + SQL scripts
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  agent:
    build: .
    env_file: .env
    environment:
      PGHOST: db
    depends_on:
      db:
        condition: service_healthy
    profiles: ["dev"]

volumes:
  db_data:  # ensures that Postgres data survives container rebuilds